### ISSUE TITLE
Doof errors when websocket connection is closed

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#156]
> 2018-06-13T11:47:38.215866+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-06-13T11:47:38.215868+00:00 app[web.1]: 
2018-06-13T11:47:38.215902+00:00 app[web.1]: Traceback (most recent call last):
2018-06-13T11:47:38.215936+00:00 app[web.1]:   File "bot.py", line 995, in <module>
2018-06-13T11:47:38.216622+00:00 app[web.1]:     main()
2018-06-13T11:47:38.216658+00:00 app[web.1]:   File "bot.py", line 988, in main
2018-06-13T11:47:38.217366+00:00 app[web.1]:     loop.run_until_complete(connect_to_message_server(loop))
2018-06-13T11:47:38.217404+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
2018-06-13T11:47:38.221804+00:00 app[web.1]:     return future.result()
2018-06-13T11:47:38.221852+00:00 app[web.1]:   File "bot.py", line 979, in connect_to_message_server
2018-06-13T11:47:38.222573+00:00 app[web.1]:     app.stop()

**Comment by noisecapella** [comment]
Closing until I see this again
