### ISSUE TITLE
Fix intermittent release failure

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#212]
We are occasionally seeing an error when starting a new release. Stack trace:

    2019-12-23T19:03:01.480481+00:00 app[web.1]: Exception found when handling a message
    2019-12-23T19:03:01.480496+00:00 app[web.1]: Traceback (most recent call last):
    2019-12-23T19:03:01.480499+00:00 app[web.1]: File "/app/release.py", line 63, in init_working_dir
    2019-12-23T19:03:01.480501+00:00 app[web.1]: yield directory
    2019-12-23T19:03:01.480503+00:00 app[web.1]: File "bot.py", line 634, in commits_since_last_release
    2019-12-23T19:03:01.480506+00:00 app[web.1]: has_new_commits = await any_new_commits(last_version, base_branch="master")
    2019-12-23T19:03:01.480508+00:00 app[web.1]: File "/app/release.py", line 180, in any_new_commits
    2019-12-23T19:03:01.480511+00:00 app[web.1]: output = await check_output(["git", "rev-list", "--count", f"v{version}..{base_branch}", "--"])
    2019-12-23T19:03:01.480513+00:00 app[web.1]: File "/app/async_subprocess.py", line 31, in check_output
    2019-12-23T19:03:01.480515+00:00 app[web.1]: raise subprocess.CalledProcessError(returncode, args[0])
    2019-12-23T19:03:01.480517+00:00 app[web.1]: subprocess.CalledProcessError: Command 'git' returned non-zero exit status 128.
    2019-12-23T19:03:01.480519+00:00 app[web.1]: 
    2019-12-23T19:03:01.480521+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2019-12-23T19:03:01.480523+00:00 app[web.1]: 
    2019-12-23T19:03:01.480525+00:00 app[web.1]: Traceback (most recent call last):
    2019-12-23T19:03:01.480527+00:00 app[web.1]: File "bot.py", line 1032, in handle_message
    2019-12-23T19:03:01.480528+00:00 app[web.1]: loop=loop
    2019-12-23T19:03:01.480530+00:00 app[web.1]: File "bot.py", line 1004, in run_command
    2019-12-23T19:03:01.480531+00:00 app[web.1]: manager=manager,
    2019-12-23T19:03:01.480533+00:00 app[web.1]: File "bot.py", line 634, in commits_since_last_release
    2019-12-23T19:03:01.480534+00:00 app[web.1]: has_new_commits = await any_new_commits(last_version, base_branch="master")
    2019-12-23T19:03:01.480536+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/contextlib.py", line 188, in __aexit__
    2019-12-23T19:03:01.480537+00:00 app[web.1]: await self.gen.athrow(typ, value, traceback)
    2019-12-23T19:03:01.480539+00:00 app[web.1]: File "/app/release.py", line 65, in init_working_dir
    2019-12-23T19:03:01.480540+00:00 app[web.1]: os.chdir(pwd)
    2019-12-23T19:03:01.480547+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5oluq4n8'

**Comment by noisecapella** [comment]
Ugh... this is a reenterant bug. `os.chdir` will not work with coroutines, we need to pass in the current directory to each command.
