### ISSUE TITLE
Handle intermittent timeouts better

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#332]
I saw this error on doof which occurred during an RC deployment (stack trace below). We should figure out how to handle this more gracefully. A couple ideas:
 - Wait 30 seconds, restart the HTTP request 2 more times or so until it succeeds. We would need to discriminate between HTTP responses with a non-200 status code and a timeout, and only retry on timeout (I think that's `RemoteDisconnected`?)
 - If there is an exception during `run_release_lifecycle`, wait then rerun it to pick up where we left off. We should keep count of the number of times an exception is triggered so we can handle servers which are non-responsive gracefully

.

    2021-05-26T18:08:22.604981+00:00 app[web.1]: Task exception was never retrieved
    2021-05-26T18:08:22.604996+00:00 app[web.1]: future: <Task finished name='Task-2' coro=<Bot.run_release_lifecycle() done, defined at /app/bot.py:316> exception=ConnectionError(ProtocolError('Connection a
    borted.', RemoteDisconnected('Remote end closed connection without response')))>
    2021-05-26T18:08:22.604996+00:00 app[web.1]: Traceback (most recent call last):
    2021-05-26T18:08:22.604997+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    2021-05-26T18:08:22.604997+00:00 app[web.1]: httplib_response = self._make_request(
    2021-05-26T18:08:22.604998+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    2021-05-26T18:08:22.604998+00:00 app[web.1]: six.raise_from(e, None)
    2021-05-26T18:08:22.604998+00:00 app[web.1]: File "<string>", line 3, in raise_from
    2021-05-26T18:08:22.604999+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    2021-05-26T18:08:22.604999+00:00 app[web.1]: httplib_response = conn.getresponse()
    2021-05-26T18:08:22.605000+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/http/client.py", line 1347, in getresponse
    2021-05-26T18:08:22.605000+00:00 app[web.1]: response.begin()
    2021-05-26T18:08:22.605000+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/http/client.py", line 307, in begin
    2021-05-26T18:08:22.605001+00:00 app[web.1]: version, status, reason = self._read_status()
    2021-05-26T18:08:22.605001+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/http/client.py", line 276, in _read_status
    2021-05-26T18:08:22.605002+00:00 app[web.1]: raise RemoteDisconnected("Remote end closed connection without"
    2021-05-26T18:08:22.605002+00:00 app[web.1]: http.client.RemoteDisconnected: Remote end closed connection without response
    2021-05-26T18:08:22.605002+00:00 app[web.1]: 
    2021-05-26T18:08:22.605002+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2021-05-26T18:08:22.605003+00:00 app[web.1]: 
    2021-05-26T18:08:22.605003+00:00 app[web.1]: Traceback (most recent call last):
    2021-05-26T18:08:22.605003+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    2021-05-26T18:08:22.605003+00:00 app[web.1]: resp = conn.urlopen(
    2021-05-26T18:08:22.605004+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    2021-05-26T18:08:22.605004+00:00 app[web.1]: retries = retries.increment(
    2021-05-26T18:08:22.605004+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    2021-05-26T18:08:22.605004+00:00 app[web.1]: raise six.reraise(type(error), error, _stacktrace)
    2021-05-26T18:08:22.605004+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    2021-05-26T18:08:22.605004+00:00 app[web.1]: raise value.with_traceback(tb)
    2021-05-26T18:08:22.605005+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    2021-05-26T18:08:22.605005+00:00 app[web.1]: httplib_response = self._make_request(
    2021-05-26T18:08:22.605005+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    2021-05-26T18:08:22.605005+00:00 app[web.1]: six.raise_from(e, None)
    2021-05-26T18:08:22.605005+00:00 app[web.1]: File "<string>", line 3, in raise_from
    2021-05-26T18:08:22.605005+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    2021-05-26T18:08:22.605005+00:00 app[web.1]: httplib_response = conn.getresponse()
    2021-05-26T18:08:22.605006+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/http/client.py", line 1347, in getresponse
    2021-05-26T18:08:22.605006+00:00 app[web.1]: response.begin()
    2021-05-26T18:08:22.605006+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/http/client.py", line 307, in begin
    2021-05-26T18:08:22.605006+00:00 app[web.1]: version, status, reason = self._read_status()
    2021-05-26T18:08:22.605006+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/http/client.py", line 276, in _read_status
    2021-05-26T18:08:22.605006+00:00 app[web.1]: raise RemoteDisconnected("Remote end closed connection without"
    2021-05-26T18:08:22.605007+00:00 app[web.1]: urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
    2021-05-26T18:08:22.605007+00:00 app[web.1]: 
    2021-05-26T18:08:22.605007+00:00 app[web.1]: During handling of the above exception, another exception occurred:
    2021-05-26T18:08:22.605008+00:00 app[web.1]: 
    2021-05-26T18:08:22.605008+00:00 app[web.1]: Traceback (most recent call last):
    2021-05-26T18:08:22.605008+00:00 app[web.1]: File "/app/bot.py", line 336, in run_release_lifecycle
    2021-05-26T18:08:22.605008+00:00 app[web.1]: await self._wait_for_deploy_rc(repo_info=repo_info, manager=manager, release_pr=release_pr)
    2021-05-26T18:08:22.605008+00:00 app[web.1]: File "/app/bot.py", line 445, in _wait_for_deploy_rc
    2021-05-26T18:08:22.605008+00:00 app[web.1]: await wait_for_deploy(
    2021-05-26T18:08:22.605009+00:00 app[web.1]: File "/app/wait_for_deploy.py", line 40, in wait_for_deploy
    2021-05-26T18:08:22.605009+00:00 app[web.1]: while await fetch_release_hash(hash_url) != latest_hash:
    2021-05-26T18:08:22.605009+00:00 app[web.1]: File "/app/wait_for_deploy.py", line 12, in fetch_release_hash
    2021-05-26T18:08:22.605009+00:00 app[web.1]: response = await client.get(hash_url)
    2021-05-26T18:08:22.605009+00:00 app[web.1]: File "/app/client_wrapper.py", line 10, in get
    2021-05-26T18:08:22.605010+00:00 app[web.1]: return requests.get(*args, **kwargs)
    2021-05-26T18:08:22.605010+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/api.py", line 76, in get
    2021-05-26T18:08:22.605010+00:00 app[web.1]: return request('get', url, params=params, **kwargs)
    2021-05-26T18:08:22.605010+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/api.py", line 61, in request
    2021-05-26T18:08:22.605010+00:00 app[web.1]: return session.request(method=method, url=url, **kwargs)
    2021-05-26T18:08:22.605010+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    2021-05-26T18:08:22.605010+00:00 app[web.1]: resp = self.send(prep, **send_kwargs)
    2021-05-26T18:08:22.605014+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    2021-05-26T18:08:22.605014+00:00 app[web.1]: r = adapter.send(request, **kwargs)
    2021-05-26T18:08:22.605015+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    2021-05-26T18:08:22.605015+00:00 app[web.1]: raise ConnectionError(err, request=request)
    2021-05-26T18:08:22.605015+00:00 app[web.1]: requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
    2021-05-26T18:10:42.420795+00:00 heroku[router]: at=info method=POST path="/api/v0/events/" host=odl-release-bot.herokuapp.com request_id=49ea8c97-d9a4-4904-a6bb-3a73d29defa9 fwd="3.93.239.51" dyno=web.1 connect=0ms service=2ms status=200 bytes=161 protocol=https
    2021-05-26T18:10:44.630730+00:00 heroku[router]: at=info method=POST path="/api/v0/events/" host=odl-release-bot.herokuapp.com request_id=1e33b958-b1fd-440c-8235-d6d9686516c1 fwd="3.84.219.176" dyno=web.1 connect=0ms service=2ms status=200 bytes=161 protocol=https
    2021-05-26T18:11:27.843086+00:00 app[api]: Starting process with command `bash` by user gschneel@mit.edu
    2021-05-26T18:11:32.500119+00:00 heroku[run.5739]: Awaiting client
    2021-05-26T18:11:32.515481+00:00 heroku[run.5739]: Starting process with command `bash`
    2021-05-26T18:11:32.671404+00:00 heroku[run.5739]: State changed from starting to up
    2021-05-26T18:12:51.223134+00:00 heroku[run.5739]: Process exited with status 127
    2021-05-26T18:12:51.317769+00:00 heroku[run.5739]: State changed from up to complete

**Comment by noisecapella** [comment]
Another intermittent issue I saw:

    2021-06-02T13:13:44.212518+00:00 app[web.1]: Task exception was never retrieved
    2021-06-02T13:13:44.212532+00:00 app[web.1]: future: <Task finished name='Task-643' coro=<Bot.handle_webhook() done, defined at /app/bot.py:1248> exception=HTTPError('503 Server Error: first byte timeout for url: https://xpro.mit.edu/static/hash.txt')>
    2021-06-02T13:13:44.212532+00:00 app[web.1]: Traceback (most recent call last):
    2021-06-02T13:13:44.212532+00:00 app[web.1]: File "/app/bot.py", line 1272, in handle_webhook
    2021-06-02T13:13:44.212533+00:00 app[web.1]: await self.finish_release(CommandArgs(
    2021-06-02T13:13:44.212533+00:00 app[web.1]: File "/app/bot.py", line 769, in finish_release
    2021-06-02T13:13:44.212533+00:00 app[web.1]: await self.run_release_lifecycle(
    2021-06-02T13:13:44.212534+00:00 app[web.1]: File "/app/bot.py", line 343, in run_release_lifecycle
    2021-06-02T13:13:44.212534+00:00 app[web.1]: await self._wait_for_deploy_prod(repo_info=repo_info, manager=manager, release_pr=release_pr)
    2021-06-02T13:13:44.212535+00:00 app[web.1]: File "/app/bot.py", line 479, in _wait_for_deploy_prod
    2021-06-02T13:13:44.212535+00:00 app[web.1]: await wait_for_deploy(
    2021-06-02T13:13:44.212536+00:00 app[web.1]: File "/app/wait_for_deploy.py", line 40, in wait_for_deploy
    2021-06-02T13:13:44.212536+00:00 app[web.1]: while await fetch_release_hash(hash_url) != latest_hash:
    2021-06-02T13:13:44.212537+00:00 app[web.1]: File "/app/wait_for_deploy.py", line 13, in fetch_release_hash
    2021-06-02T13:13:44.212537+00:00 app[web.1]: response.raise_for_status()
    2021-06-02T13:13:44.212537+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    2021-06-02T13:13:44.212538+00:00 app[web.1]: raise HTTPError(http_error_msg, response=self)
    2021-06-02T13:13:44.212538+00:00 app[web.1]: requests.exceptions.HTTPError: 503 Server Error: first byte timeout for url: https://xpro.mit.edu/static/hash.txt
