### ISSUE TITLE
Error starting a release

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#351]
2021-09-27T15:34:44.901111+00:00 app[web.1]: Traceback (most recent call last):
    2021-09-27T15:34:44.901112+00:00 app[web.1]: File "/app/bot.py", line 1442, in handle_webhook
    2021-09-27T15:34:44.901113+00:00 app[web.1]: await self.release_command(
    2021-09-27T15:34:44.901113+00:00 app[web.1]: File "/app/bot.py", line 559, in release_command
    2021-09-27T15:34:44.901113+00:00 app[web.1]: await self._new_release(
    2021-09-27T15:34:44.901114+00:00 app[web.1]: File "/app/bot.py", line 528, in _new_release
    2021-09-27T15:34:44.901114+00:00 app[web.1]: await self._web_application_release(
    2021-09-27T15:34:44.901115+00:00 app[web.1]: File "/app/bot.py", line 439, in _web_application_release
    2021-09-27T15:34:44.901115+00:00 app[web.1]: pr_number=release_pr.number,
    2021-09-27T15:34:44.901115+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'number'

**Comment by noisecapella** [comment]
This is probably a race condition where the release PR was created and then an API request was made to retrieve information about it, but it wasn't available yet. Probably a rare problem
